name: spendwise
description: A personal finance tracker app - Master Your Money
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0
  excel: ^4.0.6
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  mailer: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
